security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto

  firewalls:
    redoc:
      pattern: ^/redoc
      http_basic: ~
      provider: in_memory

    # ... inne firewalle (np. dev, main itd.)

  access_control:
    - { path: ^/redoc, roles: ROLE_API_DOC }

  providers:
    in_memory:
      memory:
        users:
          docuser:
            password: '$2y$13$Ww0yaRAyaztUQ2zKUy2HzecBIW9jx6/3X7PtBWv8DUczvD54T1xuC' # hasło: "secret"
            roles: 'ROLE_API_DOC'