version: "3.9"
services:
    app:
        build:
            context: .
        ports:
            - "8080:8080"
        depends_on:
            - queue
            - redis

    queue:
        image: laravelsail/php81-composer:latest
        command: php artisan horizon
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - redis

    redis:
        image: redis:7
