version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: fixmymind-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fixmymind-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: fixmymind-db
    environment:
      POSTGRES_DB: fixmymind
      POSTGRES_USER: fixmymind
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fixmymind-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redisdata:
