services:
  app:
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env

  queue:
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fixmymind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
