openapi: 3.0.3
info:
  title: 'Laravel API Documentation'
  description: 'API terapeutyczne do rozmów z AI'
  version: 1.0.0
servers:
  -
    url: 'http://local.fixmymind.org:8000'
tags:
  -
    name: Chat
    description: ''
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: apiKey
      name: Authorization
      in: header
      description: 'Use Basic Auth with your credentials (username:password encoded in Base64).'
security:
  -
    default: []
paths:
  /api/health:
    get:
      summary: Healthcheck
      operationId: healthcheck
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: ok
                properties:
                  status:
                    type: string
                    example: ok
      tags:
        - Chat
      security: []
  /api/chat:
    post:
      summary: ''
      operationId: postApiChat
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
