name: Deploy Test

on:
  push:
    branches:
      - test

jobs:
  deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      env-name: test
    secrets:
      APP_KEY: ${{ secrets.APP_KEY_TEST }}
      APP_URL: "https://test-api.fixmymind.org"
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_JWK_URL: ${{ secrets.SUPABASE_JWK_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
